# Generated by Django 4.1.7 on 2023-02-25 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student2',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=40)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=40)),
                ('pass_date', models.DateField()),
                ('adm_dateTime_field', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
