# Generated by Django 4.1.7 on 2023-02-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_student2_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll', models.IntegerField(unique=True)),
                ('city', models.CharField(max_length=40)),
                ('marks', models.IntegerField()),
                ('grade', models.CharField(max_length=40)),
                ('pass_date', models.DateField()),
                ('adm_dateTime_field', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Student2',
        ),
    ]
