# Generated by Django 4.1.7 on 2023-02-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70)),
                ('student_roll', models.IntegerField()),
                ('student_marks', models.IntegerField()),
                ('student_grade', models.CharField(max_length=40)),
            ],
        ),
    ]
