# Generated by Django 4.1.7 on 2023-02-27 21:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyStudent',
            fields=[
            ],
            options={
                'ordering': ['student_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('enroll.studentenrollment',),
            managers=[
                ('students', django.db.models.manager.Manager()),
            ],
        ),
    ]
