# Generated by Django 4.1.7 on 2023-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0002_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
