# Generated by Django 4.1.7 on 2023-02-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0003_alter_student_name_alter_student_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
